### ISSUE TITLE
Page de Listagem de anúncios

### ISSUE THREAD

**Issue by LeGorge** [ES2-UFPI/CADE#17]
Criar uma page do ionic para listagem de anúncios;

- Atualizar navegação do app principal
- Deve conter o arrow-back no canto superior esquerdo que mostra um modal de confirmação e em caso positivo cancela o cadastro e volta para a page principal

**Comment by LeGorge** [comment]
Na verdade, acho que essa page deve ser a página principal do app

**Comment by rodrigodz1** [comment]
Esse arrow-back será exibido após a pessoa clicar em um anúncio? (tendo a opção de voltar para a página principal)
Ou se trata da situação em que a pessoa não encontra nenhum anúncio, tenta criar o seu anúncio e então desiste do cadastro de um novo anúncio e recebe um modal de confirmação?

**Comment by LeGorge** [comment]
Nao nao rodrigo, o arrow back era para o caso de essa tela não ser a tela principal, como ela é não precisa voltar pra lugar nenhum

**Comment by LeGorge** [comment]
Erro aparecendo no console:
<ion-refresher> must be used inside an <ion-content>

Qual o objetivo desse componente? "ion-refresher"

**Comment by rodrigodz1** [comment]
Esse ion-refresher era tipo pra ficar atualizando a página constantemente, eu não tinha muita certeza, li isso no docs (https://ionicframework.com/docs/api/refresher) por isso ia pedir pra vcs revisarem

**Comment by LeGorge** [comment]
Huumm entendi, boa funcionalidade, então tu deve mexer nessa parte quando tiver trabalhando na outra issue..., beleza, mas como o erro mostrou, tu precisa botar o componente ion-refresher dentro da tag ion-content e não em ion-footer como tu botou. 
PS. Tu pode ver esses erros aparecendo na devtab do chrome

**Comment by rodrigodz1** [comment]
Ok, é que eu tinha imaginado ele como um botão, por isso criei uma footer! Vou corrigir
